[package]
name = "newsapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.121"
ureq = "2.10.0"
thiserror = "1.0.63"
termimad = "0.29.4"
crossterm = "0.27.0"
